---
abstract: 'collects and reports statistics on perl code'
author:
  - 'Christian Walde <mithaldu@yahoo.de>'
build_requires:
  FileHandle: 0
  Test::Builder::Module: 0
  Test::Class: 0
  Test::Differences: 0
  Test::MockObject: 0
  Test::More: 0
  Test::Perl::Critic::Progressive: 0
  Test::Simple: 0.96
  Try::Tiny: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.102160'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Code-Statistics
no_index:
  directory:
    - t
requires:
  App::Cmd::Setup: 0
  Carp: 0
  Clone: 0
  Config::INI::Reader: 0
  Data::Section: 0
  File::Find::Rule: 0
  File::Find::Rule::Perl: 0
  File::HomeDir: 0
  File::Slurp: 0
  Hash::Merge: 0
  JSON: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Pluggable: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::HasDefaults::RO: 0
  MooseX::SlurpyConstructor: 1.1
  PPI::Document: 0
  Path::Class: 0
  Perl::Critic::Utils::McCabe: 0
  Template: 0
  Term::ProgressBar::Simple: 0
  perl: 5.006_003
resources:
  repository: http://github.com/wchristian/code-statistics.git
version: 1.102520
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: AutoVersion
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: AutoPrereq
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Readme
      name: Readme
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: ExtraTests
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: KwaliteeTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::ProgCriticTests
      name: ProgCriticTests
      version: 1.101601
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 1.101550
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102221
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102221
